workflows:
  android-deploy-workflow:
    name: Android Deployment Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    triggering:
        events:
          - tag
        cancel_previous_builds: true
    environment:
        groups:
          - google_credentials
        flutter: stable
        xcode: latest
        cocoapods: default
    scripts:
        - name: Setup the Keystore
          script: |
            echo $KEYSTORE_FILE | base64 --decode > /tmp/foreseetest_keystore.jks
            cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
            storePassword=$KEYSTORE_STORE_PASSWORD
            keyPassword=$KEYSTORE_KEY_PASSWORD
            keyAlias=foreseetest_keystore
            storeFile=/tmp/foreseetest_keystore.jks
            EOF

        - name: Build Android App Bundle AAB
          script: |
            cd $CM_BUILD_DIR
            flutter packages pub get
            flutter build appbundle
    artifacts:
        - build/**/outputs/**/*.aab
    publishing:
        google_play:
          credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
          track: draft
